   version: "3.7"
   services:
     minio:
       image: minio/minio
       ports:
         - "9000:9000"
         - "9001:9001"
       environment:
         MINIO_ROOT_USER: chani
         MINIO_ROOT_PASSWORD: 1234567890
       volumes:
         - ./data:/data
       command: server /data --console-address ":9001"